In [1]:
import pandas as pd

In [2]:
gc = pd.read_csv('Geo_map.csv')

In [3]:
gc

,Trukker Geo map Expressions,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,Sno.,Country,City,Locations,Geolocation Coordinates,NaN
1,NaN,NaN,NaN,NaN,Latitude,Longitude
2,1,India,Bangalore,Bangalore,12° 58' 20.7912'' N,77° 34' 50.3148'' E
3,2,UAE,Dubai,JLT Head Office Dubai,"25° 4' 3.612"" N","55° 8' 19.8096"" E"
4,3,UAE,Ras Al Khaima,Rak,25° 48' 2.4984'' N,55° 58' 34.3200'' E
5,4,UAE,Dubai,Aweer,"25° 10' 32.52"" N","55° 20' 53.16"" E"
6,5,UAE,Abhu Dhabi,Maffraq,"24° 28' 0.0012"" N","54° 22' 0.0012"" E"
7,6,UAE,Abhu Dhabi,Adnoc 893,24° 27' 41.5260'' N,54° 19' 23.7972'' E
8,7,Bahrain,Sitra,Sitra,"26° 08' 60.00"" N","50° 36' 59.99"" E"
9,8,Turkey,Istanbul,Istanbul,41° 0' 54.4932'' N,28° 58' 46.3080'' E
10,9,Oman,Muscat,Muscat,23° 36' 51.5808'' N,58° 32' 43.0224'' E
11,10,Oman,Sohar,Sohar,"24° 21' 59.99"" N","56° 44' 59.99"" E"
12,11,Oman,Salalah,Salalah,"17° 00' 54.18"" N","54° 05' 32.53"" E"
13,12,KSA,Jeddah,Jeddah,21° 29' 33.0000'' N,39° 10' 39.2520'' E
14,13,KSA,Yanbu,Yanbu,24° 11' 12.6528'' N,38° 1' 35.1408'' E
15,14,KSA,Dammam,Dammam,26° 23' 57.3000'' N,49° 59' 3.6960'' E
16,15,KSA,Riyadh,Riyadh,24° 46' 27.3540'' N,46° 44' 18.9096'' E
17,16,KSA,Jubail,Jubail,"27° 00' 40.39"" N","49° 39' 29.70"" E"
18,17,Jordan,Amman,Amman,31° 57' 47.3688'' N,35° 55' 49.2924'' E
19,18,Jordan,Sahab,Sahab,"31° 52' 1.20"" N","36° 00' 0.00"" E"
20,19,Poland,Warsaw,Warsaw,52° 11' 46.3812'' N,21° 10' 41.6100'' E
21,20,Kazakhstan,Almaty,Almaty,43° 14' 20.2164'' N,76° 53' 22.9524'' E
22,21,Egypt,Cairo,Cario,30° 1' 59.9988'' N,31° 14' 0.0024'' E
23,22,Egypt,Alexandria,Alexandria,31° 12' 20.7108'' N,29° 55' 28.2936'' E
24,23,Egypt,Damietta,Damietta,31° 25' 3.1440'' N,31° 48' 51.9984'' E
25,24,Egypt,Ain Sokhna,Ain Sokhna,"29° 36' 0.65"" N","32° 19' 0.16"" E"
26,25,Egypt,Port Said,Port Said,"31° 15' 23.54"" N","32° 17' 2.80"" E"
27,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
gc.columns=['S.no','Country','City','Locations','Latitude','Longitude']

In [5]:
gc

,S.no,Country,City,Locations,Latitude,Longitude
0,Sno.,Country,City,Locations,Geolocation Coordinates,NaN
1,NaN,NaN,NaN,NaN,Latitude,Longitude
2,1,India,Bangalore,Bangalore,12° 58' 20.7912'' N,77° 34' 50.3148'' E
3,2,UAE,Dubai,JLT Head Office Dubai,"25° 4' 3.612"" N","55° 8' 19.8096"" E"
4,3,UAE,Ras Al Khaima,Rak,25° 48' 2.4984'' N,55° 58' 34.3200'' E
5,4,UAE,Dubai,Aweer,"25° 10' 32.52"" N","55° 20' 53.16"" E"
6,5,UAE,Abhu Dhabi,Maffraq,"24° 28' 0.0012"" N","54° 22' 0.0012"" E"
7,6,UAE,Abhu Dhabi,Adnoc 893,24° 27' 41.5260'' N,54° 19' 23.7972'' E
8,7,Bahrain,Sitra,Sitra,"26° 08' 60.00"" N","50° 36' 59.99"" E"
9,8,Turkey,Istanbul,Istanbul,41° 0' 54.4932'' N,28° 58' 46.3080'' E
10,9,Oman,Muscat,Muscat,23° 36' 51.5808'' N,58° 32' 43.0224'' E
11,10,Oman,Sohar,Sohar,"24° 21' 59.99"" N","56° 44' 59.99"" E"
12,11,Oman,Salalah,Salalah,"17° 00' 54.18"" N","54° 05' 32.53"" E"
13,12,KSA,Jeddah,Jeddah,21° 29' 33.0000'' N,39° 10' 39.2520'' E
14,13,KSA,Yanbu,Yanbu,24° 11' 12.6528'' N,38° 1' 35.1408'' E
15,14,KSA,Dammam,Dammam,26° 23' 57.3000'' N,49° 59' 3.6960'' E
16,15,KSA,Riyadh,Riyadh,24° 46' 27.3540'' N,46° 44' 18.9096'' E
17,16,KSA,Jubail,Jubail,"27° 00' 40.39"" N","49° 39' 29.70"" E"
18,17,Jordan,Amman,Amman,31° 57' 47.3688'' N,35° 55' 49.2924'' E
19,18,Jordan,Sahab,Sahab,"31° 52' 1.20"" N","36° 00' 0.00"" E"
20,19,Poland,Warsaw,Warsaw,52° 11' 46.3812'' N,21° 10' 41.6100'' E
21,20,Kazakhstan,Almaty,Almaty,43° 14' 20.2164'' N,76° 53' 22.9524'' E
22,21,Egypt,Cairo,Cario,30° 1' 59.9988'' N,31° 14' 0.0024'' E
23,22,Egypt,Alexandria,Alexandria,31° 12' 20.7108'' N,29° 55' 28.2936'' E
24,23,Egypt,Damietta,Damietta,31° 25' 3.1440'' N,31° 48' 51.9984'' E
25,24,Egypt,Ain Sokhna,Ain Sokhna,"29° 36' 0.65"" N","32° 19' 0.16"" E"
26,25,Egypt,Port Said,Port Said,"31° 15' 23.54"" N","32° 17' 2.80"" E"
27,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
gc = gc.drop(gc.index[0])

In [7]:
gc

,S.no,Country,City,Locations,Latitude,Longitude
1,NaN,NaN,NaN,NaN,Latitude,Longitude
2,1,India,Bangalore,Bangalore,12° 58' 20.7912'' N,77° 34' 50.3148'' E
3,2,UAE,Dubai,JLT Head Office Dubai,"25° 4' 3.612"" N","55° 8' 19.8096"" E"
4,3,UAE,Ras Al Khaima,Rak,25° 48' 2.4984'' N,55° 58' 34.3200'' E
5,4,UAE,Dubai,Aweer,"25° 10' 32.52"" N","55° 20' 53.16"" E"
6,5,UAE,Abhu Dhabi,Maffraq,"24° 28' 0.0012"" N","54° 22' 0.0012"" E"
7,6,UAE,Abhu Dhabi,Adnoc 893,24° 27' 41.5260'' N,54° 19' 23.7972'' E
8,7,Bahrain,Sitra,Sitra,"26° 08' 60.00"" N","50° 36' 59.99"" E"
9,8,Turkey,Istanbul,Istanbul,41° 0' 54.4932'' N,28° 58' 46.3080'' E
10,9,Oman,Muscat,Muscat,23° 36' 51.5808'' N,58° 32' 43.0224'' E
11,10,Oman,Sohar,Sohar,"24° 21' 59.99"" N","56° 44' 59.99"" E"
12,11,Oman,Salalah,Salalah,"17° 00' 54.18"" N","54° 05' 32.53"" E"
13,12,KSA,Jeddah,Jeddah,21° 29' 33.0000'' N,39° 10' 39.2520'' E
14,13,KSA,Yanbu,Yanbu,24° 11' 12.6528'' N,38° 1' 35.1408'' E
15,14,KSA,Dammam,Dammam,26° 23' 57.3000'' N,49° 59' 3.6960'' E
16,15,KSA,Riyadh,Riyadh,24° 46' 27.3540'' N,46° 44' 18.9096'' E
17,16,KSA,Jubail,Jubail,"27° 00' 40.39"" N","49° 39' 29.70"" E"
18,17,Jordan,Amman,Amman,31° 57' 47.3688'' N,35° 55' 49.2924'' E
19,18,Jordan,Sahab,Sahab,"31° 52' 1.20"" N","36° 00' 0.00"" E"
20,19,Poland,Warsaw,Warsaw,52° 11' 46.3812'' N,21° 10' 41.6100'' E
21,20,Kazakhstan,Almaty,Almaty,43° 14' 20.2164'' N,76° 53' 22.9524'' E
22,21,Egypt,Cairo,Cario,30° 1' 59.9988'' N,31° 14' 0.0024'' E
23,22,Egypt,Alexandria,Alexandria,31° 12' 20.7108'' N,29° 55' 28.2936'' E
24,23,Egypt,Damietta,Damietta,31° 25' 3.1440'' N,31° 48' 51.9984'' E
25,24,Egypt,Ain Sokhna,Ain Sokhna,"29° 36' 0.65"" N","32° 19' 0.16"" E"
26,25,Egypt,Port Said,Port Said,"31° 15' 23.54"" N","32° 17' 2.80"" E"
27,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
gc = gc.drop(gc.index[0])

In [9]:
gc

,S.no,Country,City,Locations,Latitude,Longitude
2,1,India,Bangalore,Bangalore,12° 58' 20.7912'' N,77° 34' 50.3148'' E
3,2,UAE,Dubai,JLT Head Office Dubai,"25° 4' 3.612"" N","55° 8' 19.8096"" E"
4,3,UAE,Ras Al Khaima,Rak,25° 48' 2.4984'' N,55° 58' 34.3200'' E
5,4,UAE,Dubai,Aweer,"25° 10' 32.52"" N","55° 20' 53.16"" E"
6,5,UAE,Abhu Dhabi,Maffraq,"24° 28' 0.0012"" N","54° 22' 0.0012"" E"
7,6,UAE,Abhu Dhabi,Adnoc 893,24° 27' 41.5260'' N,54° 19' 23.7972'' E
8,7,Bahrain,Sitra,Sitra,"26° 08' 60.00"" N","50° 36' 59.99"" E"
9,8,Turkey,Istanbul,Istanbul,41° 0' 54.4932'' N,28° 58' 46.3080'' E
10,9,Oman,Muscat,Muscat,23° 36' 51.5808'' N,58° 32' 43.0224'' E
11,10,Oman,Sohar,Sohar,"24° 21' 59.99"" N","56° 44' 59.99"" E"
12,11,Oman,Salalah,Salalah,"17° 00' 54.18"" N","54° 05' 32.53"" E"
13,12,KSA,Jeddah,Jeddah,21° 29' 33.0000'' N,39° 10' 39.2520'' E
14,13,KSA,Yanbu,Yanbu,24° 11' 12.6528'' N,38° 1' 35.1408'' E
15,14,KSA,Dammam,Dammam,26° 23' 57.3000'' N,49° 59' 3.6960'' E
16,15,KSA,Riyadh,Riyadh,24° 46' 27.3540'' N,46° 44' 18.9096'' E
17,16,KSA,Jubail,Jubail,"27° 00' 40.39"" N","49° 39' 29.70"" E"
18,17,Jordan,Amman,Amman,31° 57' 47.3688'' N,35° 55' 49.2924'' E
19,18,Jordan,Sahab,Sahab,"31° 52' 1.20"" N","36° 00' 0.00"" E"
20,19,Poland,Warsaw,Warsaw,52° 11' 46.3812'' N,21° 10' 41.6100'' E
21,20,Kazakhstan,Almaty,Almaty,43° 14' 20.2164'' N,76° 53' 22.9524'' E
22,21,Egypt,Cairo,Cario,30° 1' 59.9988'' N,31° 14' 0.0024'' E
23,22,Egypt,Alexandria,Alexandria,31° 12' 20.7108'' N,29° 55' 28.2936'' E
24,23,Egypt,Damietta,Damietta,31° 25' 3.1440'' N,31° 48' 51.9984'' E
25,24,Egypt,Ain Sokhna,Ain Sokhna,"29° 36' 0.65"" N","32° 19' 0.16"" E"
26,25,Egypt,Port Said,Port Said,"31° 15' 23.54"" N","32° 17' 2.80"" E"
27,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
gc.set_index('S.no',inplace=True)

In [11]:
gc

,Country,City,Locations,Latitude,Longitude
S.no,,,,,
1,India,Bangalore,Bangalore,12° 58' 20.7912'' N,77° 34' 50.3148'' E
2,UAE,Dubai,JLT Head Office Dubai,"25° 4' 3.612"" N","55° 8' 19.8096"" E"
3,UAE,Ras Al Khaima,Rak,25° 48' 2.4984'' N,55° 58' 34.3200'' E
4,UAE,Dubai,Aweer,"25° 10' 32.52"" N","55° 20' 53.16"" E"
5,UAE,Abhu Dhabi,Maffraq,"24° 28' 0.0012"" N","54° 22' 0.0012"" E"
6,UAE,Abhu Dhabi,Adnoc 893,24° 27' 41.5260'' N,54° 19' 23.7972'' E
7,Bahrain,Sitra,Sitra,"26° 08' 60.00"" N","50° 36' 59.99"" E"
8,Turkey,Istanbul,Istanbul,41° 0' 54.4932'' N,28° 58' 46.3080'' E
9,Oman,Muscat,Muscat,23° 36' 51.5808'' N,58° 32' 43.0224'' E
10,Oman,Sohar,Sohar,"24° 21' 59.99"" N","56° 44' 59.99"" E"
11,Oman,Salalah,Salalah,"17° 00' 54.18"" N","54° 05' 32.53"" E"
12,KSA,Jeddah,Jeddah,21° 29' 33.0000'' N,39° 10' 39.2520'' E
13,KSA,Yanbu,Yanbu,24° 11' 12.6528'' N,38° 1' 35.1408'' E
14,KSA,Dammam,Dammam,26° 23' 57.3000'' N,49° 59' 3.6960'' E
15,KSA,Riyadh,Riyadh,24° 46' 27.3540'' N,46° 44' 18.9096'' E
16,KSA,Jubail,Jubail,"27° 00' 40.39"" N","49° 39' 29.70"" E"
17,Jordan,Amman,Amman,31° 57' 47.3688'' N,35° 55' 49.2924'' E
18,Jordan,Sahab,Sahab,"31° 52' 1.20"" N","36° 00' 0.00"" E"
19,Poland,Warsaw,Warsaw,52° 11' 46.3812'' N,21° 10' 41.6100'' E
20,Kazakhstan,Almaty,Almaty,43° 14' 20.2164'' N,76° 53' 22.9524'' E
21,Egypt,Cairo,Cario,30° 1' 59.9988'' N,31° 14' 0.0024'' E
22,Egypt,Alexandria,Alexandria,31° 12' 20.7108'' N,29° 55' 28.2936'' E
23,Egypt,Damietta,Damietta,31° 25' 3.1440'' N,31° 48' 51.9984'' E
24,Egypt,Ain Sokhna,Ain Sokhna,"29° 36' 0.65"" N","32° 19' 0.16"" E"
25,Egypt,Port Said,Port Said,"31° 15' 23.54"" N","32° 17' 2.80"" E"
NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
gc = gc.drop(gc.index[25])

In [37]:
gc

,Country,City,Locations,Latitude,Longitude
S.no,,,,,
1,India,Bangalore,Bangalore,12° 58' 20.7912'' N,77° 34' 50.3148'' E
2,UAE,Dubai,JLT Head Office Dubai,"25° 4' 3.612"" N","55° 8' 19.8096"" E"
3,UAE,Ras Al Khaima,Rak,25° 48' 2.4984'' N,55° 58' 34.3200'' E
4,UAE,Dubai,Aweer,"25° 10' 32.52"" N","55° 20' 53.16"" E"
5,UAE,Abhu Dhabi,Maffraq,"24° 28' 0.0012"" N","54° 22' 0.0012"" E"
6,UAE,Abhu Dhabi,Adnoc 893,24° 27' 41.5260'' N,54° 19' 23.7972'' E
7,Bahrain,Sitra,Sitra,"26° 08' 60.00"" N","50° 36' 59.99"" E"
8,Turkey,Istanbul,Istanbul,41° 0' 54.4932'' N,28° 58' 46.3080'' E
9,Oman,Muscat,Muscat,23° 36' 51.5808'' N,58° 32' 43.0224'' E
10,Oman,Sohar,Sohar,"24° 21' 59.99"" N","56° 44' 59.99"" E"
11,Oman,Salalah,Salalah,"17° 00' 54.18"" N","54° 05' 32.53"" E"
12,KSA,Jeddah,Jeddah,21° 29' 33.0000'' N,39° 10' 39.2520'' E
13,KSA,Yanbu,Yanbu,24° 11' 12.6528'' N,38° 1' 35.1408'' E
14,KSA,Dammam,Dammam,26° 23' 57.3000'' N,49° 59' 3.6960'' E
15,KSA,Riyadh,Riyadh,24° 46' 27.3540'' N,46° 44' 18.9096'' E
16,KSA,Jubail,Jubail,"27° 00' 40.39"" N","49° 39' 29.70"" E"
17,Jordan,Amman,Amman,31° 57' 47.3688'' N,35° 55' 49.2924'' E
18,Jordan,Sahab,Sahab,"31° 52' 1.20"" N","36° 00' 0.00"" E"
19,Poland,Warsaw,Warsaw,52° 11' 46.3812'' N,21° 10' 41.6100'' E
20,Kazakhstan,Almaty,Almaty,43° 14' 20.2164'' N,76° 53' 22.9524'' E
21,Egypt,Cairo,Cario,30° 1' 59.9988'' N,31° 14' 0.0024'' E
22,Egypt,Alexandria,Alexandria,31° 12' 20.7108'' N,29° 55' 28.2936'' E
23,Egypt,Damietta,Damietta,31° 25' 3.1440'' N,31° 48' 51.9984'' E
24,Egypt,Ain Sokhna,Ain Sokhna,"29° 36' 0.65"" N","32° 19' 0.16"" E"
25,Egypt,Port Said,Port Said,"31° 15' 23.54"" N","32° 17' 2.80"" E"

In [12]:
from geopy.geocoders import ArcGIS

In [13]:
nom = ArcGIS()

In [14]:
s = nom.geocode('Noida')

In [15]:
s

Location(Noida, Gautam Buddha Nagar, Uttar Pradesh, (28.53342, 77.3819, 0.0))

In [16]:
s.latitude

28.53342

In [17]:
s.longitude

77.3819

In [18]:
pip install folium

Requirement already satisfied: folium in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (0.14.0)
Requirement already satisfied: branca>=0.6.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from folium) (0.6.0)
Requirement already satisfied: jinja2>=2.9 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from folium) (3.1.2)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from folium) (1.25.1)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from folium) (2.28.2)
Requirement already satisfied: MarkupSafe>=2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from jinja2>=2.9->folium) (2.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->folium) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->folium) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->folium) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->folium) (2022.12.7)
Note: you may need to restart the kernel to use updated packages.

In [19]:
pip install --upgrade pip

Requirement already satisfied: pip in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (23.2.1)
Note: you may need to restart the kernel to use updated packages.

In [20]:
import folium

In [21]:
map = folium.Map(location=[28.53342,77.3819])

In [22]:
map

In [23]:
map.add_child(folium.Marker(location=[28.53342,77.3819],popup='Noida 74',icon=folium.Icon(color = 'orange')))

In [46]:
a_list = gc[['City','latitude','longitude']].values.tolist()

In [47]:
a_list

[['Bangalore', 12.96614, 77.58694],
 ['Dubai', 25.26951, 55.30884],
 ['Ras Al Khaima ', 25.66667, 56.0],
 ['Dubai', 25.26951, 55.30884],
 ['Abhu Dhabi ', 24.46918, 54.37173],
 ['Abhu Dhabi ', 24.46918, 54.37173],
 ['Sitra ', 11.04143, 77.03775],
 ['Istanbul ', 41.06201, 28.98877],
 ['Muscat ', 23.61523, 58.59126],
 ['Sohar ', 24.34973, 56.73212],
 ['Salalah', 17.01492, 54.09301],
 ['Jeddah', 21.4817, 39.1828],
 ['Yanbu', 24.08954, 38.0618],
 ['Dammam', 26.43683, 50.09083],
 ['Riyadh', 24.68204, 46.68725],
 ['Jubail ', 27.0174, 49.62251],
 ['Amman ', 31.9518, 35.94042],
 ['Sahab', 31.87032, 36.00479],
 ['Warsaw', 52.229827082, 21.011731518],
 ['Almaty ', 43.25066, 76.88814],
 ['Cairo ', 30.04427, 31.23525],
 ['Alexandria', 31.2105, 29.91253],
 ['Damietta', 31.41648, 31.81332],
 ['Ain Sokhna ', 29.58902, 32.33597],
 ['Port Said ', 31.26004, 32.28612]]

In [27]:
fg = folium.FeatureGroup(name='tiger_reserve')

fg.add_child(folium.Marker(location=[28.53342,77.3819],popup='Noida 74',icon=folium.Icon(color = 'orange')))

map.add_child(fg)

In [30]:
def new_square(num):
    return num**2

In [31]:
new_square(5)

25

In [32]:
s = lambda x: x**2

In [33]:
s(4)

16

In [42]:
gc['latitude'] = gc['Coordinates'].apply(lambda x: x.latitude)
gc['longitude'] = gc['Coordinates'].apply(lambda x: x.longitude)

In [38]:
gc['City'].apply(nom.geocode)

S.no
1     (Bangalore, Bengaluru, Karnataka, (12.96614, 7...
2                         (Dubai, (25.26951, 55.30884))
3                     (Ras al Khaima, (25.66667, 56.0))
4                         (Dubai, (25.26951, 55.30884))
5                     (Abu Dhabi, (24.46918, 54.37173))
6                     (Abu Dhabi, (24.46918, 54.37173))
7     (Sitra, Civil Aerodrome, Coimbatore, Tamil Nad...
8     (İstanbul, Şişli, İstanbul, (41.06201, 28.98877))
9                        (Muscat, (23.61523, 58.59126))
10      (Sohar, Al Batinah North, (24.34973, 56.73212))
11              (Salalah, Dhofar, (17.01492, 54.09301))
12                         (Jeddah, (21.4817, 39.1828))
13                         (Yanbu, (24.08954, 38.0618))
14                       (Dammam, (26.43683, 50.09083))
15                       (Riyadh, (24.68204, 46.68725))
16                        (Jubail, (27.0174, 49.62251))
17      (Amman, Amman Governorate, (31.9518, 35.94042))
18                 (Saḩāb, Amman, (31.87032, 36.00479))
19    (Warsaw, Warszawa, Mazowieckie, (52.229827082,...
20                       (Almaty, (43.25066, 76.88814))
21                        (Cairo, (30.04427, 31.23525))
22                    (Alexandria, (31.2105, 29.91253))
23                     (Damietta, (31.41648, 31.81332))
24        (Ain Sokhna, As Suways, (29.58902, 32.33597))
25                    (Port Said, (31.26004, 32.28612))
Name: City, dtype: object

In [39]:
gc['Coordinates'] = gc['City'].apply(nom.geocode)

In [40]:
gc['Coordinates'].values

array([Location(Bangalore, Bengaluru, Karnataka, (12.96614, 77.58694, 0.0)),
       Location(Dubai, (25.26951, 55.30884, 0.0)),
       Location(Ras al Khaima, (25.66667, 56.0, 0.0)),
       Location(Dubai, (25.26951, 55.30884, 0.0)),
       Location(Abu Dhabi, (24.46918, 54.37173, 0.0)),
       Location(Abu Dhabi, (24.46918, 54.37173, 0.0)),
       Location(Sitra, Civil Aerodrome, Coimbatore, Tamil Nadu, (11.04143, 77.03775, 0.0)),
       Location(İstanbul, Şişli, İstanbul, (41.06201, 28.98877, 0.0)),
       Location(Muscat, (23.61523, 58.59126, 0.0)),
       Location(Sohar, Al Batinah North, (24.34973, 56.73212, 0.0)),
       Location(Salalah, Dhofar, (17.01492, 54.09301, 0.0)),
       Location(Jeddah, (21.4817, 39.1828, 0.0)),
       Location(Yanbu, (24.08954, 38.0618, 0.0)),
       Location(Dammam, (26.43683, 50.09083, 0.0)),
       Location(Riyadh, (24.68204, 46.68725, 0.0)),
       Location(Jubail, (27.0174, 49.62251, 0.0)),
       Location(Amman, Amman Governorate, (31.9518, 35.94042, 0.0)),
       Location(Saḩāb, Amman, (31.87032, 36.00479, 0.0)),
       Location(Warsaw, Warszawa, Mazowieckie, (52.229827082, 21.011731518, 0.0)),
       Location(Almaty, (43.25066, 76.88814, 0.0)),
       Location(Cairo, (30.04427, 31.23525, 0.0)),
       Location(Alexandria, (31.2105, 29.91253, 0.0)),
       Location(Damietta, (31.41648, 31.81332, 0.0)),
       Location(Ain Sokhna, As Suways, (29.58902, 32.33597, 0.0)),
       Location(Port Said, (31.26004, 32.28612, 0.0))], dtype=object)

In [43]:
gc

,Country,City,Locations,Latitude,Longitude,Coordinates,latitude,longitude
S.no,,,,,,,,
1,India,Bangalore,Bangalore,12° 58' 20.7912'' N,77° 34' 50.3148'' E,"(Bangalore, Bengaluru, Karnataka, (12.96614, 7...",12.966140,77.586940
2,UAE,Dubai,JLT Head Office Dubai,"25° 4' 3.612"" N","55° 8' 19.8096"" E","(Dubai, (25.26951, 55.30884))",25.269510,55.308840
3,UAE,Ras Al Khaima,Rak,25° 48' 2.4984'' N,55° 58' 34.3200'' E,"(Ras al Khaima, (25.66667, 56.0))",25.666670,56.000000
4,UAE,Dubai,Aweer,"25° 10' 32.52"" N","55° 20' 53.16"" E","(Dubai, (25.26951, 55.30884))",25.269510,55.308840
5,UAE,Abhu Dhabi,Maffraq,"24° 28' 0.0012"" N","54° 22' 0.0012"" E","(Abu Dhabi, (24.46918, 54.37173))",24.469180,54.371730
6,UAE,Abhu Dhabi,Adnoc 893,24° 27' 41.5260'' N,54° 19' 23.7972'' E,"(Abu Dhabi, (24.46918, 54.37173))",24.469180,54.371730
7,Bahrain,Sitra,Sitra,"26° 08' 60.00"" N","50° 36' 59.99"" E","(Sitra, Civil Aerodrome, Coimbatore, Tamil Nad...",11.041430,77.037750
8,Turkey,Istanbul,Istanbul,41° 0' 54.4932'' N,28° 58' 46.3080'' E,"(İstanbul, Şişli, İstanbul, (41.06201, 28.98877))",41.062010,28.988770
9,Oman,Muscat,Muscat,23° 36' 51.5808'' N,58° 32' 43.0224'' E,"(Muscat, (23.61523, 58.59126))",23.615230,58.591260
10,Oman,Sohar,Sohar,"24° 21' 59.99"" N","56° 44' 59.99"" E","(Sohar, Al Batinah North, (24.34973, 56.73212))",24.349730,56.732120
11,Oman,Salalah,Salalah,"17° 00' 54.18"" N","54° 05' 32.53"" E","(Salalah, Dhofar, (17.01492, 54.09301))",17.014920,54.093010
12,KSA,Jeddah,Jeddah,21° 29' 33.0000'' N,39° 10' 39.2520'' E,"(Jeddah, (21.4817, 39.1828))",21.481700,39.182800
13,KSA,Yanbu,Yanbu,24° 11' 12.6528'' N,38° 1' 35.1408'' E,"(Yanbu, (24.08954, 38.0618))",24.089540,38.061800
14,KSA,Dammam,Dammam,26° 23' 57.3000'' N,49° 59' 3.6960'' E,"(Dammam, (26.43683, 50.09083))",26.436830,50.090830
15,KSA,Riyadh,Riyadh,24° 46' 27.3540'' N,46° 44' 18.9096'' E,"(Riyadh, (24.68204, 46.68725))",24.682040,46.687250
16,KSA,Jubail,Jubail,"27° 00' 40.39"" N","49° 39' 29.70"" E","(Jubail, (27.0174, 49.62251))",27.017400,49.622510
17,Jordan,Amman,Amman,31° 57' 47.3688'' N,35° 55' 49.2924'' E,"(Amman, Amman Governorate, (31.9518, 35.94042))",31.951800,35.940420
18,Jordan,Sahab,Sahab,"31° 52' 1.20"" N","36° 00' 0.00"" E","(Saḩāb, Amman, (31.87032, 36.00479))",31.870320,36.004790
19,Poland,Warsaw,Warsaw,52° 11' 46.3812'' N,21° 10' 41.6100'' E,"(Warsaw, Warszawa, Mazowieckie, (52.229827082,...",52.229827,21.011732
20,Kazakhstan,Almaty,Almaty,43° 14' 20.2164'' N,76° 53' 22.9524'' E,"(Almaty, (43.25066, 76.88814))",43.250660,76.888140
21,Egypt,Cairo,Cario,30° 1' 59.9988'' N,31° 14' 0.0024'' E,"(Cairo, (30.04427, 31.23525))",30.044270,31.235250
22,Egypt,Alexandria,Alexandria,31° 12' 20.7108'' N,29° 55' 28.2936'' E,"(Alexandria, (31.2105, 29.91253))",31.210500,29.912530
23,Egypt,Damietta,Damietta,31° 25' 3.1440'' N,31° 48' 51.9984'' E,"(Damietta, (31.41648, 31.81332))",31.416480,31.813320
24,Egypt,Ain Sokhna,Ain Sokhna,"29° 36' 0.65"" N","32° 19' 0.16"" E","(Ain Sokhna, As Suways, (29.58902, 32.33597))",29.589020,32.335970
25,Egypt,Port Said,Port Said,"31° 15' 23.54"" N","32° 17' 2.80"" E","(Port Said, (31.26004, 32.28612))",31.260040,32.286120

In [44]:
gc.drop(['Latitude','Longitude'], axis =1, inplace=True)

In [45]:
gc

,Country,City,Locations,Coordinates,latitude,longitude
S.no,,,,,,
1,India,Bangalore,Bangalore,"(Bangalore, Bengaluru, Karnataka, (12.96614, 7...",12.966140,77.586940
2,UAE,Dubai,JLT Head Office Dubai,"(Dubai, (25.26951, 55.30884))",25.269510,55.308840
3,UAE,Ras Al Khaima,Rak,"(Ras al Khaima, (25.66667, 56.0))",25.666670,56.000000
4,UAE,Dubai,Aweer,"(Dubai, (25.26951, 55.30884))",25.269510,55.308840
5,UAE,Abhu Dhabi,Maffraq,"(Abu Dhabi, (24.46918, 54.37173))",24.469180,54.371730
6,UAE,Abhu Dhabi,Adnoc 893,"(Abu Dhabi, (24.46918, 54.37173))",24.469180,54.371730
7,Bahrain,Sitra,Sitra,"(Sitra, Civil Aerodrome, Coimbatore, Tamil Nad...",11.041430,77.037750
8,Turkey,Istanbul,Istanbul,"(İstanbul, Şişli, İstanbul, (41.06201, 28.98877))",41.062010,28.988770
9,Oman,Muscat,Muscat,"(Muscat, (23.61523, 58.59126))",23.615230,58.591260
10,Oman,Sohar,Sohar,"(Sohar, Al Batinah North, (24.34973, 56.73212))",24.349730,56.732120
11,Oman,Salalah,Salalah,"(Salalah, Dhofar, (17.01492, 54.09301))",17.014920,54.093010
12,KSA,Jeddah,Jeddah,"(Jeddah, (21.4817, 39.1828))",21.481700,39.182800
13,KSA,Yanbu,Yanbu,"(Yanbu, (24.08954, 38.0618))",24.089540,38.061800
14,KSA,Dammam,Dammam,"(Dammam, (26.43683, 50.09083))",26.436830,50.090830
15,KSA,Riyadh,Riyadh,"(Riyadh, (24.68204, 46.68725))",24.682040,46.687250
16,KSA,Jubail,Jubail,"(Jubail, (27.0174, 49.62251))",27.017400,49.622510
17,Jordan,Amman,Amman,"(Amman, Amman Governorate, (31.9518, 35.94042))",31.951800,35.940420
18,Jordan,Sahab,Sahab,"(Saḩāb, Amman, (31.87032, 36.00479))",31.870320,36.004790
19,Poland,Warsaw,Warsaw,"(Warsaw, Warszawa, Mazowieckie, (52.229827082,...",52.229827,21.011732
20,Kazakhstan,Almaty,Almaty,"(Almaty, (43.25066, 76.88814))",43.250660,76.888140
21,Egypt,Cairo,Cario,"(Cairo, (30.04427, 31.23525))",30.044270,31.235250
22,Egypt,Alexandria,Alexandria,"(Alexandria, (31.2105, 29.91253))",31.210500,29.912530
23,Egypt,Damietta,Damietta,"(Damietta, (31.41648, 31.81332))",31.416480,31.813320
24,Egypt,Ain Sokhna,Ain Sokhna,"(Ain Sokhna, As Suways, (29.58902, 32.33597))",29.589020,32.335970
25,Egypt,Port Said,Port Said,"(Port Said, (31.26004, 32.28612))",31.260040,32.286120

In [50]:
import folium 
Global_Coordinates_map = folium.Map(location=[31.260040	,32.286120])
fg = folium.FeatureGroup(name='Gl_Cod')

for i in a_list:
    fg.add_child(folium.Marker(location = [i[1],i[2]], popup=i[0], icon=folium.Icon(color='orange')))
Global_Coordinates_map.add_child(fg)
Global_Coordinates_map.save('Gl_Cod.html')

In [ ]:
N = int(input())

import numpy as np
np.random.seed(N)

random_list = np.random.randint(90,100,1500)
freq={}

for item in random_list:
    if item in freq:
        freq[item]+=1
    else:
        freq[item]=1
print(freq)