In [3]:
from geopy.geocoders import ArcGIS

In [2]:
pip install geopy

Collecting geopy
  Downloading geopy-2.3.0-py3-none-any.whl (119 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.8/119.8 kB 1.4 MB/s eta 0:00:00[31m1.5 MB/s eta 0:00:01
Collecting geographiclib<3,>=1.52 (from geopy)
  Downloading geographiclib-2.0-py3-none-any.whl (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.3/40.3 kB 1.3 MB/s eta 0:00:00
Installing collected packages: geographiclib, geopy
Successfully installed geographiclib-2.0 geopy-2.3.0
Note: you may need to restart the kernel to use updated packages.

In [4]:
nom = ArcGIS()

In [7]:
s = nom.geocode('Bangalore')

In [8]:
s.latitude

12.96614

In [9]:
s.longitude

77.58694

In [10]:
pip install folium

Collecting folium
  Downloading folium-0.14.0-py2.py3-none-any.whl (102 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.3/102.3 kB 3.6 MB/s eta 0:00:00
Collecting branca>=0.6.0 (from folium)
  Downloading branca-0.6.0-py3-none-any.whl (24 kB)
Requirement already satisfied: jinja2>=2.9 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from folium) (3.1.2)
Collecting numpy (from folium)
  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/48/73/df07644e8fa1127a7985db70cf1d07123004e2dd7a3cf33e8b83297a775b/numpy-1.25.1-cp311-cp311-macosx_11_0_arm64.whl.metadata
  Downloading numpy-1.25.1-cp311-cp311-macosx_11_0_arm64.whl.metadata (5.6 kB)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from folium) (2.28.2)
Requirement already satisfied: MarkupSafe>=2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from jinja2>=2.9->folium) (2.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->folium) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->folium) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->folium) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->folium) (2022.12.7)
Downloading numpy-1.25.1-cp311-cp311-macosx_11_0_arm64.whl (14.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.0/14.0 MB 8.4 MB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Installing collected packages: numpy, branca, folium
Successfully installed branca-0.6.0 folium-0.14.0 numpy-1.25.1
Note: you may need to restart the kernel to use updated packages.

In [3]:
import folium

In [5]:
map = folium.Map(location=[12.96614,77.58694])

In [6]:
map

In [7]:
map.add_child(folium.Marker(location=[12.96614,77.58694],popup='tkd',icon=folium.Icon(color='orange')))

In [20]:
import pandas as pd

In [18]:
pip install pandas

SyntaxError: invalid syntax (1048225456.py, line 1)

In [19]:
pip3 install pandas

SyntaxError: invalid syntax (580609534.py, line 1)

In [21]:
geo_cod=pd.read_csv('Geo_Map_Cod.txt')

FileNotFoundError: [Errno 2] No such file or directory: 'Geo_Map_Cod.txt'

In [22]:
pwd

'/Users/kunal/Documents/My Soft /Python/TruKKer '

In [23]:
geo_cod = pd.read_csv('Geo_map.csv')

In [24]:
geo_cod

,Trukker Geo map Expressions,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,Sno.,Country,City,Locations,Geolocation Coordinates,NaN
1,NaN,NaN,NaN,NaN,Latitude,Longitude
2,1,India,Bangalore,Bangalore,12° 58' 20.7912'' N,77° 34' 50.3148'' E
3,2,UAE,Dubai,JLT Head Office Dubai,"25° 4' 3.612"" N","55° 8' 19.8096"" E"
4,3,UAE,Ras Al Khaima,Rak,25° 48' 2.4984'' N,55° 58' 34.3200'' E
5,4,UAE,Dubai,Aweer,"25° 10' 32.52"" N","55° 20' 53.16"" E"
6,5,UAE,Abhu Dhabi,Maffraq,"24° 28' 0.0012"" N","54° 22' 0.0012"" E"
7,6,UAE,Abhu Dhabi,Adnoc 893,24° 27' 41.5260'' N,54° 19' 23.7972'' E
8,7,Bahrain,Sitra,Sitra,"26° 08' 60.00"" N","50° 36' 59.99"" E"
9,8,Turkey,Istanbul,Istanbul,41° 0' 54.4932'' N,28° 58' 46.3080'' E
10,9,Oman,Muscat,Muscat,23° 36' 51.5808'' N,58° 32' 43.0224'' E
11,10,Oman,Sohar,Sohar,"24° 21' 59.99"" N","56° 44' 59.99"" E"
12,11,Oman,Salalah,Salalah,"17° 00' 54.18"" N","54° 05' 32.53"" E"
13,12,KSA,Jeddah,Jeddah,21° 29' 33.0000'' N,39° 10' 39.2520'' E
14,13,KSA,Yanbu,Yanbu,24° 11' 12.6528'' N,38° 1' 35.1408'' E
15,14,KSA,Dammam,Dammam,26° 23' 57.3000'' N,49° 59' 3.6960'' E
16,15,KSA,Riyadh,Riyadh,24° 46' 27.3540'' N,46° 44' 18.9096'' E
17,16,KSA,Jubail,Jubail,"27° 00' 40.39"" N","49° 39' 29.70"" E"
18,17,Jordan,Amman,Amman,31° 57' 47.3688'' N,35° 55' 49.2924'' E
19,18,Jordan,Sahab,Sahab,"31° 52' 1.20"" N","36° 00' 0.00"" E"
20,19,Poland,Warsaw,Warsaw,52° 11' 46.3812'' N,21° 10' 41.6100'' E
21,20,Kazakhstan,Almaty,Almaty,43° 14' 20.2164'' N,76° 53' 22.9524'' E
22,21,Egypt,Cairo,Cario,30° 1' 59.9988'' N,31° 14' 0.0024'' E
23,22,Egypt,Alexandria,Alexandria,31° 12' 20.7108'' N,29° 55' 28.2936'' E
24,23,Egypt,Damietta,Damietta,31° 25' 3.1440'' N,31° 48' 51.9984'' E
25,24,Egypt,Ain Sokhna,Ain Sokhna,"29° 36' 0.65"" N","32° 19' 0.16"" E"
26,25,Egypt,Port Said,Port Said,"31° 15' 23.54"" N","32° 17' 2.80"" E"
27,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
geo_asset = pd.read_csv('Global Assets Cost - 2020~2023.csv')

In [26]:
geo_asset

,\nGLOBAL ADMIN COST CONSOLIDATION,Countries / FIN POC /HR POC,SREEJITH/RAM (INDIA),Unnamed: 3,Unnamed: 4,SREEJITH/WISSAM (UAE),Unnamed: 6,Unnamed: 7,PRIME\nSREEJITH/WISSAM (UAE),Unnamed: 9,...,BURGA/YESIM(TURKEY),Unnamed: 27,Unnamed: 28,BURGA/YESIM(KZK),Unnamed: 30,Unnamed: 31,BURGA/NATALIA(POLAND),Unnamed: 33,Unnamed: 34,Status
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Asset Type,Apr '20 ~ Mar '21,Apr '21 ~ Mar '22,Apr '22 ~ Mar '23,Apr '20 ~ Mar '21,Apr '21 ~ Mar '22,Apr '22 ~ Mar '23,Apr '20 ~ Mar '21,Apr '21 ~ Mar '22,...,Apr '20 ~ Mar '21,Apr '21 ~ Mar '22,Apr '22 ~ Mar '23,Apr '20 ~ Mar '21,Apr '21 ~ Mar '22,Apr '22 ~ Mar '23,Apr '20 ~ Mar '21,Apr '21 ~ Mar '22,Apr '22 ~ Mar '23,NaN
2,IT Assets,Mobile,759,"9,549",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"11,061","3,067",NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Network Providers -SIM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Laptop,"75,105","1,32,091","42,162",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"2,806","31,349","1,802","4,083",NaN
5,NaN,"Computers - Screen, CPU, Keyboards","2,867","2,322",NaN,"28,957","1,69,733","1,30,027",NaN,NaN,...,"13,221","6,803","10,980",NaN,NaN,NaN,NaN,NaN,"5,956",NaN
6,NaN,Network Providers - Internet/WIFI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,TV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"1,375",NaN,878,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,Projectors,422,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,Camera,"1,951","7,953",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,"Printer, Copiers","1,179",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,PPT Changer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,Server Decks (DVD Inclusive),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,"Accessories - Headset, Mouse, Pods, Pendrives,...",213,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,340,"1,216",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,Conference Communicators,NaN,NaN,"4,411",NaN,NaN,NaN,NaN,NaN,...,NaN,600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,Annual Main Cost,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,Speakers,NaN,NaN,"2,014",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Services,Software Cost,NaN,979,NaN,"35,589",NaN,NaN,NaN,NaN,...,"40,275","2,254",NaN,NaN,NaN,429,NaN,NaN,NaN,NaN
18,NaN,"Employee Welfare Petty Cash - Cakes, Snack, Fo...","3,668","13,712","15,192","6,002","11,389","8,451",NaN,"1,100",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,"Update, License renewel",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"10,326","4,081",NaN
20,NaN,Insurances,"4,488","7,697","13,609","1,47,603","2,66,066","4,92,510",NaN,"53,803",...,NaN,NaN,NaN,NaN,NaN,146,NaN,NaN,NaN,NaN
21,NaN,Travel Ticket & Visa,71,"7,406","10,559","18,243","72,714","76,233",NaN,"1,473",...,NaN,NaN,NaN,NaN,NaN,242,NaN,NaN,NaN,NaN
22,NaN,"Company Vehicles, 2W 4W",NaN,NaN,NaN,"1,27,205","26,509","1,62,608",NaN,NaN,...,"2,83,229","3,493",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,Accomodation Cost,NaN,"10,388","10,785","18,792","24,154","23,665",NaN,"1,944",...,NaN,NaN,NaN,NaN,NaN,66,NaN,NaN,NaN,NaN
24,NaN,Govt Fees if any,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN
25,NaN,Third Part Auditing Fee,"2,439","2,439",NaN,"10,218","50,218","75,422",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,"14,178",NaN,NaN,NaN,NaN
26,NaN,"Rental Cars, Plans",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,Antivirus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Non-IT Assets,"Building Rent, Leases cost","28,537","1,06,633","1,55,047","46,331","10,708","93,145",NaN,"16,433",...,NaN,NaN,NaN,NaN,NaN,"11,023",NaN,NaN,NaN,NaN
29,NaN,COMPANY TRUCKS,NaN,NaN,"93,877",NaN,NaN,NaN,NaN,"30,99,787",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,Legal Docs Service Cost,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"3,430",NaN,NaN,NaN,NaN,"4,407",NaN,NaN,NaN,NaN
31,NaN,Advance Property,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,Parking - 2W&4W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,Fridge,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,370,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,CCTV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,292,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,Biometric Punching Machine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,Furniture,NaN,NaN,"53,059","1,710","2,00,656","47,407",NaN,"10,655",...,"17,815","5,619","8,503",NaN,NaN,"2,217",NaN,NaN,NaN,NaN
37,NaN,"Stationery - Total Cost (Pen, Pencil, Paper, M...",95,"2,145","4,220","4,213","3,097","6,103",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,274,NaN,NaN,NaN,NaN
38,NaN,"Restroom Supplies - Tissues, Sanitizers, Handw...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"2,244","3,402","3,067",NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,Room Freshner's,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,Pedestal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,Cupboards,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,286,NaN,NaN,NaN,NaN
42,NaN,"Coffee Machine, Supplies like Milk, Water, Cof...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,Fire Extinguishers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,Gifts,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,Air Conditioner,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,Sign Board,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,NaN,Water Cooler,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,NaN,Counting machine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,NaN,NaN,"1,21,792","3,03,312","4,04,936","4,44,864","8,35,244","11,15,572",0,"31,85,194",...,"3,62,664","34,449","26,866",0,0,"36,077","31,349","12,128","14,121",NaN
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,606800000,NaN,NaN,NaN,NaN,NaN
54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
geo_cod.columns=['Sno.','Country','City','Locations']

ValueError: Length mismatch: Expected axis has 6 elements, new values have 4 elements

In [29]:
geo_cod.columns=['S.no','Country','City','Locations','Latitude','Longitude']

In [30]:
geo_cod

,S.no,Country,City,Locations,Latitude,Longitude
0,Sno.,Country,City,Locations,Geolocation Coordinates,NaN
1,NaN,NaN,NaN,NaN,Latitude,Longitude
2,1,India,Bangalore,Bangalore,12° 58' 20.7912'' N,77° 34' 50.3148'' E
3,2,UAE,Dubai,JLT Head Office Dubai,"25° 4' 3.612"" N","55° 8' 19.8096"" E"
4,3,UAE,Ras Al Khaima,Rak,25° 48' 2.4984'' N,55° 58' 34.3200'' E
5,4,UAE,Dubai,Aweer,"25° 10' 32.52"" N","55° 20' 53.16"" E"
6,5,UAE,Abhu Dhabi,Maffraq,"24° 28' 0.0012"" N","54° 22' 0.0012"" E"
7,6,UAE,Abhu Dhabi,Adnoc 893,24° 27' 41.5260'' N,54° 19' 23.7972'' E
8,7,Bahrain,Sitra,Sitra,"26° 08' 60.00"" N","50° 36' 59.99"" E"
9,8,Turkey,Istanbul,Istanbul,41° 0' 54.4932'' N,28° 58' 46.3080'' E
10,9,Oman,Muscat,Muscat,23° 36' 51.5808'' N,58° 32' 43.0224'' E
11,10,Oman,Sohar,Sohar,"24° 21' 59.99"" N","56° 44' 59.99"" E"
12,11,Oman,Salalah,Salalah,"17° 00' 54.18"" N","54° 05' 32.53"" E"
13,12,KSA,Jeddah,Jeddah,21° 29' 33.0000'' N,39° 10' 39.2520'' E
14,13,KSA,Yanbu,Yanbu,24° 11' 12.6528'' N,38° 1' 35.1408'' E
15,14,KSA,Dammam,Dammam,26° 23' 57.3000'' N,49° 59' 3.6960'' E
16,15,KSA,Riyadh,Riyadh,24° 46' 27.3540'' N,46° 44' 18.9096'' E
17,16,KSA,Jubail,Jubail,"27° 00' 40.39"" N","49° 39' 29.70"" E"
18,17,Jordan,Amman,Amman,31° 57' 47.3688'' N,35° 55' 49.2924'' E
19,18,Jordan,Sahab,Sahab,"31° 52' 1.20"" N","36° 00' 0.00"" E"
20,19,Poland,Warsaw,Warsaw,52° 11' 46.3812'' N,21° 10' 41.6100'' E
21,20,Kazakhstan,Almaty,Almaty,43° 14' 20.2164'' N,76° 53' 22.9524'' E
22,21,Egypt,Cairo,Cario,30° 1' 59.9988'' N,31° 14' 0.0024'' E
23,22,Egypt,Alexandria,Alexandria,31° 12' 20.7108'' N,29° 55' 28.2936'' E
24,23,Egypt,Damietta,Damietta,31° 25' 3.1440'' N,31° 48' 51.9984'' E
25,24,Egypt,Ain Sokhna,Ain Sokhna,"29° 36' 0.65"" N","32° 19' 0.16"" E"
26,25,Egypt,Port Said,Port Said,"31° 15' 23.54"" N","32° 17' 2.80"" E"
27,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
geo_cod = geo_cod.drop(geo_cod.index[0])

In [36]:
geo_cod = geo_cod.drop(geo_cod.index[1])

In [38]:
geo_cod = geo_cod.drop(geo_cod.index[0])

In [37]:
geo_cod

,S.no,Country,City,Locations,Latitude,Longitude
1,NaN,NaN,NaN,NaN,Latitude,Longitude
3,2,UAE,Dubai,JLT Head Office Dubai,"25° 4' 3.612"" N","55° 8' 19.8096"" E"
4,3,UAE,Ras Al Khaima,Rak,25° 48' 2.4984'' N,55° 58' 34.3200'' E
5,4,UAE,Dubai,Aweer,"25° 10' 32.52"" N","55° 20' 53.16"" E"
6,5,UAE,Abhu Dhabi,Maffraq,"24° 28' 0.0012"" N","54° 22' 0.0012"" E"
7,6,UAE,Abhu Dhabi,Adnoc 893,24° 27' 41.5260'' N,54° 19' 23.7972'' E
8,7,Bahrain,Sitra,Sitra,"26° 08' 60.00"" N","50° 36' 59.99"" E"
9,8,Turkey,Istanbul,Istanbul,41° 0' 54.4932'' N,28° 58' 46.3080'' E
10,9,Oman,Muscat,Muscat,23° 36' 51.5808'' N,58° 32' 43.0224'' E
11,10,Oman,Sohar,Sohar,"24° 21' 59.99"" N","56° 44' 59.99"" E"
12,11,Oman,Salalah,Salalah,"17° 00' 54.18"" N","54° 05' 32.53"" E"
13,12,KSA,Jeddah,Jeddah,21° 29' 33.0000'' N,39° 10' 39.2520'' E
14,13,KSA,Yanbu,Yanbu,24° 11' 12.6528'' N,38° 1' 35.1408'' E
15,14,KSA,Dammam,Dammam,26° 23' 57.3000'' N,49° 59' 3.6960'' E
16,15,KSA,Riyadh,Riyadh,24° 46' 27.3540'' N,46° 44' 18.9096'' E
17,16,KSA,Jubail,Jubail,"27° 00' 40.39"" N","49° 39' 29.70"" E"
18,17,Jordan,Amman,Amman,31° 57' 47.3688'' N,35° 55' 49.2924'' E
19,18,Jordan,Sahab,Sahab,"31° 52' 1.20"" N","36° 00' 0.00"" E"
20,19,Poland,Warsaw,Warsaw,52° 11' 46.3812'' N,21° 10' 41.6100'' E
21,20,Kazakhstan,Almaty,Almaty,43° 14' 20.2164'' N,76° 53' 22.9524'' E
22,21,Egypt,Cairo,Cario,30° 1' 59.9988'' N,31° 14' 0.0024'' E
23,22,Egypt,Alexandria,Alexandria,31° 12' 20.7108'' N,29° 55' 28.2936'' E
24,23,Egypt,Damietta,Damietta,31° 25' 3.1440'' N,31° 48' 51.9984'' E
25,24,Egypt,Ain Sokhna,Ain Sokhna,"29° 36' 0.65"" N","32° 19' 0.16"" E"
26,25,Egypt,Port Said,Port Said,"31° 15' 23.54"" N","32° 17' 2.80"" E"
27,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
geo_cod

,S.no,Country,City,Locations,Latitude,Longitude
3,2,UAE,Dubai,JLT Head Office Dubai,"25° 4' 3.612"" N","55° 8' 19.8096"" E"
4,3,UAE,Ras Al Khaima,Rak,25° 48' 2.4984'' N,55° 58' 34.3200'' E
5,4,UAE,Dubai,Aweer,"25° 10' 32.52"" N","55° 20' 53.16"" E"
6,5,UAE,Abhu Dhabi,Maffraq,"24° 28' 0.0012"" N","54° 22' 0.0012"" E"
7,6,UAE,Abhu Dhabi,Adnoc 893,24° 27' 41.5260'' N,54° 19' 23.7972'' E
8,7,Bahrain,Sitra,Sitra,"26° 08' 60.00"" N","50° 36' 59.99"" E"
9,8,Turkey,Istanbul,Istanbul,41° 0' 54.4932'' N,28° 58' 46.3080'' E
10,9,Oman,Muscat,Muscat,23° 36' 51.5808'' N,58° 32' 43.0224'' E
11,10,Oman,Sohar,Sohar,"24° 21' 59.99"" N","56° 44' 59.99"" E"
12,11,Oman,Salalah,Salalah,"17° 00' 54.18"" N","54° 05' 32.53"" E"
13,12,KSA,Jeddah,Jeddah,21° 29' 33.0000'' N,39° 10' 39.2520'' E
14,13,KSA,Yanbu,Yanbu,24° 11' 12.6528'' N,38° 1' 35.1408'' E
15,14,KSA,Dammam,Dammam,26° 23' 57.3000'' N,49° 59' 3.6960'' E
16,15,KSA,Riyadh,Riyadh,24° 46' 27.3540'' N,46° 44' 18.9096'' E
17,16,KSA,Jubail,Jubail,"27° 00' 40.39"" N","49° 39' 29.70"" E"
18,17,Jordan,Amman,Amman,31° 57' 47.3688'' N,35° 55' 49.2924'' E
19,18,Jordan,Sahab,Sahab,"31° 52' 1.20"" N","36° 00' 0.00"" E"
20,19,Poland,Warsaw,Warsaw,52° 11' 46.3812'' N,21° 10' 41.6100'' E
21,20,Kazakhstan,Almaty,Almaty,43° 14' 20.2164'' N,76° 53' 22.9524'' E
22,21,Egypt,Cairo,Cario,30° 1' 59.9988'' N,31° 14' 0.0024'' E
23,22,Egypt,Alexandria,Alexandria,31° 12' 20.7108'' N,29° 55' 28.2936'' E
24,23,Egypt,Damietta,Damietta,31° 25' 3.1440'' N,31° 48' 51.9984'' E
25,24,Egypt,Ain Sokhna,Ain Sokhna,"29° 36' 0.65"" N","32° 19' 0.16"" E"
26,25,Egypt,Port Said,Port Said,"31° 15' 23.54"" N","32° 17' 2.80"" E"
27,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
geo_cod.set_index('S.no',inplace=True)

In [41]:
geo_cod

,Country,City,Locations,Latitude,Longitude
S.no,,,,,
2,UAE,Dubai,JLT Head Office Dubai,"25° 4' 3.612"" N","55° 8' 19.8096"" E"
3,UAE,Ras Al Khaima,Rak,25° 48' 2.4984'' N,55° 58' 34.3200'' E
4,UAE,Dubai,Aweer,"25° 10' 32.52"" N","55° 20' 53.16"" E"
5,UAE,Abhu Dhabi,Maffraq,"24° 28' 0.0012"" N","54° 22' 0.0012"" E"
6,UAE,Abhu Dhabi,Adnoc 893,24° 27' 41.5260'' N,54° 19' 23.7972'' E
7,Bahrain,Sitra,Sitra,"26° 08' 60.00"" N","50° 36' 59.99"" E"
8,Turkey,Istanbul,Istanbul,41° 0' 54.4932'' N,28° 58' 46.3080'' E
9,Oman,Muscat,Muscat,23° 36' 51.5808'' N,58° 32' 43.0224'' E
10,Oman,Sohar,Sohar,"24° 21' 59.99"" N","56° 44' 59.99"" E"
11,Oman,Salalah,Salalah,"17° 00' 54.18"" N","54° 05' 32.53"" E"
12,KSA,Jeddah,Jeddah,21° 29' 33.0000'' N,39° 10' 39.2520'' E
13,KSA,Yanbu,Yanbu,24° 11' 12.6528'' N,38° 1' 35.1408'' E
14,KSA,Dammam,Dammam,26° 23' 57.3000'' N,49° 59' 3.6960'' E
15,KSA,Riyadh,Riyadh,24° 46' 27.3540'' N,46° 44' 18.9096'' E
16,KSA,Jubail,Jubail,"27° 00' 40.39"" N","49° 39' 29.70"" E"
17,Jordan,Amman,Amman,31° 57' 47.3688'' N,35° 55' 49.2924'' E
18,Jordan,Sahab,Sahab,"31° 52' 1.20"" N","36° 00' 0.00"" E"
19,Poland,Warsaw,Warsaw,52° 11' 46.3812'' N,21° 10' 41.6100'' E
20,Kazakhstan,Almaty,Almaty,43° 14' 20.2164'' N,76° 53' 22.9524'' E
21,Egypt,Cairo,Cario,30° 1' 59.9988'' N,31° 14' 0.0024'' E
22,Egypt,Alexandria,Alexandria,31° 12' 20.7108'' N,29° 55' 28.2936'' E
23,Egypt,Damietta,Damietta,31° 25' 3.1440'' N,31° 48' 51.9984'' E
24,Egypt,Ain Sokhna,Ain Sokhna,"29° 36' 0.65"" N","32° 19' 0.16"" E"
25,Egypt,Port Said,Port Said,"31° 15' 23.54"" N","32° 17' 2.80"" E"
NaN,NaN,NaN,NaN,NaN,NaN

In [1]:
geo_cod

NameError: name 'geo_cod' is not defined

In [1]:
import folium

# Create a map
map = folium.Map(location=[latitude, longitude], zoom_start=13)

# Create HTML code for the custom popup
popup_html = "<h3>Custom Popup</h3><p>This is a custom popup.</p>"

# Create a marker with the custom popup
marker = folium.Marker(location=[marker_latitude, marker_longitude], popup=popup_html)

# Add the marker to the map
marker.add_to(map)

# Display the map
map

NameError: name 'latitude' is not defined

In [8]:
map.add_child(folium.Marker(location=[12.96614,77.58694],popup='tkd',icon=folium.Icon(color='orange')))